// src/components/project/ProjectTemplate.jsx
// ============================================
// UNIVERSAL PROJECT TEMPLATE
// ============================================
// ⚠️ DO NOT EDIT THIS FILE
// This is a reusable template for ALL projects
// Edit your individual project files (Mh1.jsx, Mh2.jsx, etc.) instead
// ============================================

import React, { Suspense, useState, useCallback } from 'react';
import ProjectLayout from './ProjectLayout.jsx';
import { HeroContent, HeroBackground } from './ProjectComponents.jsx';
import { ScrollPrompt } from '../common/LayoutComponents.jsx';
import { useProjectAnimation, useProjectNavigation, useNavbarControl } from '../../hooks/index.js';
import { MapSection } from '../../sections/MapSection.jsx';

/**
 * ProjectTemplate - Universal component that powers all project pages
 * 
 * HOW IT WORKS:
 * - Receives configuration from project files (Mh1.jsx, Mh2.jsx, etc.)
 * - Handles all animations, navigation, and state management
 * - Renders sections based on configuration
 * 
 * YOU DON'T NEED TO EDIT THIS FILE!
 * Just pass different configs from your project files.
 */
const ProjectTemplate = ({
  // Project identification
  projectData,          // Project data object from projectsData.js
  
  // Section configuration
  totalSections = 5,    // Total number of sections
  sections = [],        // Array of section configurations
  
  // Optional configurations
  mapDescription = null,  // Description for map section
  enableNavbar = true,    // Show/hide navbar
  onSectionChange = null, // Callback when section changes
}) => {
  
  // ========================================
  // VALIDATION
  // Check that required props are provided
  // ========================================
  if (!projectData) {
    console.error('❌ ProjectTemplate: projectData is required');
    return <div style={{ color: 'white', padding: '2rem' }}>Error: Project data not found</div>;
  }

  if (!sections || sections.length === 0) {
    console.error('❌ ProjectTemplate: sections array is required');
    return <div style={{ color: 'white', padding: '2rem' }}>Error: No sections configured</div>;
  }

  // ========================================
  // STATE MANAGEMENT
  // Tracks current state of the project
  // ========================================
  const [animationPhase, setAnimationPhase] = useState('initial');
  const [currentSection, setCurrentSection] = useState(0);
  const [startMapAnimation, setStartMapAnimation] = useState(false);

  // ========================================
  // ANIMATION COMPLETION HANDLER
  // Called when hero section drag-to-unlock completes
  // ========================================
  const handleAnimationComplete = useCallback(() => {
    console.log('🎉 Hero animation complete → Moving to section 1');
    setCurrentSection(1);
    onSectionChange?.(1);
  }, [onSectionChange]);

  // ========================================
  // BACKWARD NAVIGATION HANDLER
  // Handles going back between sections
  // ========================================
  const handleGoBack = useCallback((section, setSectionCallback) => {
    console.log(`⬅️ Going back from section ${section}`);
    
    if (section === 1) {
      // Special handling: Section 1 → 0 (trigger hero return animation)
      setStartMapAnimation(false);
      handleReturnToHero();
      setCurrentSection(0);
      onSectionChange?.(0);
    } else {
      // Standard backward navigation
      const newSection = Math.max(0, section - 1);
      setSectionCallback(newSection);
      onSectionChange?.(newSection);
    }
  }, [onSectionChange]); // handleReturnToHero is defined below

  // ========================================
  // ANIMATION HOOK
  // Manages hero section timeline animations
  // ========================================
  const {
    titleOpacity,        // Controls hero title fade
    unlockProgress,      // Progress of unlock animation
    gradientOpacity,     // Controls gradient overlay
    backgroundFade,      // Controls background image fade
    dragProgress,        // Current drag progress (0-1)
    handleReturnToHero,  // Function to return to hero with animation
  } = useProjectAnimation(
    currentSection, 
    handleAnimationComplete, 
    setAnimationPhase
  );

  // ========================================
  // NAVIGATION HOOK
  // Handles keyboard shortcuts and scroll navigation
  // ========================================
  useProjectNavigation(
    totalSections, 
    animationPhase,
    handleGoBack,
    currentSection,
    setCurrentSection,
    startMapAnimation,
    setStartMapAnimation
  );

  // ========================================
  // NAVBAR CONTROL HOOK
  // Shows/hides navbar based on section and state
  // ========================================
  if (enableNavbar) {
    useNavbarControl(currentSection, animationPhase, dragProgress);
  }

  // ========================================
  // SECTION RENDERER
  // Renders different section types based on config
  // ========================================
  const renderSection = (sectionConfig, index) => {
    // Only render current section
    if (currentSection !== index) return null;

    // ----------------------------------------
    // HERO SECTION (Type: 'hero')
    // Animated landing with drag-to-unlock
    // ----------------------------------------
    if (sectionConfig.type === 'hero') {
      return (
        <section key={index} className="project-section">
          {/* Background image with fade animation */}
          <HeroBackground
            imagePath={sectionConfig.backgroundImage}
            backgroundFade={backgroundFade}
            gradientOpacity={gradientOpacity}
            visible={true}
          />

          {/* Title and subtitle with fade animation */}
          <HeroContent
            title={sectionConfig.title}
            subtitle={sectionConfig.subtitle}
            titleOpacity={titleOpacity}
          />

          {/* Drag prompt (only visible when ready) */}
          <ScrollPrompt
            dragProgress={dragProgress}
            visible={animationPhase === 'waiting'}
          />
        </section>
      );
    }

    // ----------------------------------------
    // MAP SECTION (Type: 'map')
    // Interactive map with logos and metrics
    // ----------------------------------------
    if (sectionConfig.type === 'map') {
      return (
        <section
          className="project-section"
          key={index}
          logos={sectionConfig.logos || []}>
          MapComponent={
            <Suspense fallback={
              <ComponentLoading />
            }>
              {sectionConfig.component}
            </Suspense>
          }
          description={mapDescription || sectionConfig.description}
          visible={true}
          </section>
        >
      );
    }

    // ----------------------------------------
    // CAROUSEL SECTION (Type: 'carousel')
    // 3D image gallery
    // ----------------------------------------
    if (sectionConfig.type === 'carousel') {
      return (
        <section key={index} className="project-section">
          {sectionConfig.component}
        </section>
      );
    }

    // ----------------------------------------
    // CUSTOM SECTION (Type: 'custom')
    // Any custom component you provide
    // ----------------------------------------
    if (sectionConfig.type === 'custom') {
      return (
        <section key={index} className={`project-section ${sectionConfig.className || ''}`}>
          {sectionConfig.component}
        </section>
      );
    }

    // ----------------------------------------
    // UNKNOWN SECTION TYPE
    // ----------------------------------------
    console.warn(`⚠️ Unknown section type: ${sectionConfig.type}`);
    return null;
  };

  // ========================================
  // DEBUG LOGGING (Development only)
  // ========================================
  if (process.env.NODE_ENV === 'development') {
    console.log('🔍 ProjectTemplate State:', { 
      projectId: projectData.id,
      currentSection, 
      animationPhase,
      dragProgress: dragProgress?.toFixed(2),
    });
  }

  // ========================================
  // RENDER
  // ========================================
  return (
    <ProjectLayout
      currentSection={currentSection}
      totalSections={totalSections}
      animationPhase={animationPhase}
      unlockProgress={unlockProgress}
      dragProgress={dragProgress}
      onSectionChange={setCurrentSection}
    >
      {/* Render all sections based on configuration */}
      {sections.map((sectionConfig, index) => 
        renderSection(sectionConfig, index)
      )}
    </ProjectLayout>
  );
};

export default ProjectTemplate;

/*
 * ============================================
 * HOW TO USE THIS TEMPLATE
 * ============================================
 * 
 * 1. DON'T EDIT THIS FILE
 * 2. Create your project file (e.g., Mh1.jsx)
 * 3. Pass configuration to this template
 * 
 * EXAMPLE (Mh1.jsx):
 * 
 * import ProjectTemplate from '../../components/project/ProjectTemplate';
 * 
 * const Mh1 = () => {
 *   const config = {
 *     projectData: getProjectById('mh1'),
 *     totalSections: 3,
 *     sections: [
 *       { type: 'hero', title: '...', subtitle: '...', backgroundImage: '...' },
 *       { type: 'map', component: <MyMap />, logos: [...] },
 *       { type: 'carousel', component: <Carousel data={...} /> }
 *     ],
 *     enableNavbar: true
 *   };
 *   
 *   return <ProjectTemplate {...config} />;
 * };
 * 
 * ============================================
 * SECTION TYPES SUPPORTED
 * ============================================
 * 
 * 1. 'hero' - Animated landing section
 *    Required: title, subtitle, backgroundImage
 * 
 * 2. 'map' - Interactive map section
 *    Required: component
 *    Optional: logos, description
 * 
 * 3. 'carousel' - Image carousel
 *    Required: component
 * 
 * 4. 'custom' - Any custom component
 *    Required: component
 *    Optional: className
 * 
 * ============================================
 */